In [ ]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

path = './house-votes-84.csv'
house_data = pd.read_csv(path)

house_data.head()

Class Name  handicapped-infants  water-project-cost-sharing  \
0  republican                    n                           y   
1  republican                    n                           y   
2    democrat                  NaN                           y   
3    democrat                    n                           y   
4    democrat                    y                           y   

   adoption-of-the-budget-resolution  physician-fee-freeze  el-salvador-aid  \
0                                  n                     y                y   
1                                  n                     y                y   
2                                  y                   NaN                y   
3                                  y                     n              NaN   
4                                  y                     n                y   

   religious-groups-in-schools  anti-satellite-test-ban  \
0                            y                        n   
1                            y                        n   
2                            y                        n   
3                            y                        n   
4                            y                        n   

   aid-to-nicaraguan-contras  mx-missile  immigration  \
0                          n           n            y   
1                          n           n            n   
2                          n           n            n   
3                          n           n            n   
4                          n           n            n   

   synfuels-corporation-cutback  education-spending  superfund-right-to-sue  \
0                           NaN                   y                       y   
1                             n                   y                       y   
2                             y                   n                       y   
3                             y                   n                       y   
4                             y                 NaN                       y   

   crime  duty-free-exports  export-administration-act-south-africa  
0      y                  n                                       y  
1      y                  n                                     NaN  
2      y                  n                                       n  
3      n                  n                                       y  
4      y                  y                                       y

In [ ]:
# house_data = house_data.replace(to_replace="%\?%", value=np.nan, regex=True) # Not working

# Replace '?' with NaN
house_data.replace('?', pd.NA, inplace=True)

# Save the modified DataFrame back to a CSV file
house_data.to_csv(path, index=False)


In [ ]:
house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 17 columns):
 #   Column                                   Non-Null Count  Dtype 
---  ------                                   --------------  ----- 
 0   Class Name                               435 non-null    object
 1    handicapped-infants                     423 non-null    object
 2    water-project-cost-sharing              387 non-null    object
 3    adoption-of-the-budget-resolution       424 non-null    object
 4    physician-fee-freeze                    424 non-null    object
 5    el-salvador-aid                         420 non-null    object
 6    religious-groups-in-schools             424 non-null    object
 7    anti-satellite-test-ban                 421 non-null    object
 8    aid-to-nicaraguan-contras               420 non-null    object
 9    mx-missile                              413 non-null    object
 10   immigration                             428 non-null    objec

In [ ]:
null_columns = house_data.columns[house_data.isnull().any()]
for i in list(null_columns):
  house_data[i].fillna(house_data[i].mode().values[0], inplace = True)

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

encoded_house_data = house_data.copy()

column_headers = house_data.columns.tolist()
print(column_headers)

for i in column_headers:
  encoded_house_data[i] = label_encoder.fit_transform(house_data[i])

['Class Name', ' handicapped-infants', ' water-project-cost-sharing', ' adoption-of-the-budget-resolution', ' physician-fee-freeze', ' el-salvador-aid', ' religious-groups-in-schools', ' anti-satellite-test-ban', ' aid-to-nicaraguan-contras', ' mx-missile', ' immigration', ' synfuels-corporation-cutback', ' education-spending', ' superfund-right-to-sue', ' crime', ' duty-free-exports', ' export-administration-act-south-africa']


In [ ]:
encoded_house_data.describe().T

count      mean       std  min  25%  \
Class Name                               435.0  0.386207  0.487440  0.0  0.0   
 handicapped-infants                     435.0  0.429885  0.495630  0.0  0.0   
 water-project-cost-sharing              435.0  0.558621  0.497123  0.0  0.0   
 adoption-of-the-budget-resolution       435.0  0.606897  0.489002  0.0  0.0   
 physician-fee-freeze                    435.0  0.406897  0.491821  0.0  0.0   
 el-salvador-aid                         435.0  0.521839  0.500098  0.0  0.0   
 religious-groups-in-schools             435.0  0.650575  0.477337  0.0  0.0   
 anti-satellite-test-ban                 435.0  0.581609  0.493863  0.0  0.0   
 aid-to-nicaraguan-contras               435.0  0.590805  0.492252  0.0  0.0   
 mx-missile                              435.0  0.526437  0.499876  0.0  0.0   
 immigration                             435.0  0.512644  0.500416  0.0  0.0   
 synfuels-corporation-cutback            435.0  0.344828  0.475859  0.0  0.0   
 education-spending                      435.0  0.393103  0.489002  0.0  0.0   
 superfund-right-to-sue                  435.0  0.537931  0.499133  0.0  0.0   
 crime                                   435.0  0.609195  0.488493  0.0  0.0   
 duty-free-exports                       435.0  0.400000  0.490462  0.0  0.0   
 export-administration-act-south-africa  435.0  0.857471  0.349994  0.0  1.0   

                                         50%  75%  max  
Class Name                               0.0  1.0  1.0  
 handicapped-infants                     0.0  1.0  1.0  
 water-project-cost-sharing              1.0  1.0  1.0  
 adoption-of-the-budget-resolution       1.0  1.0  1.0  
 physician-fee-freeze                    0.0  1.0  1.0  
 el-salvador-aid                         1.0  1.0  1.0  
 religious-groups-in-schools             1.0  1.0  1.0  
 anti-satellite-test-ban                 1.0  1.0  1.0  
 aid-to-nicaraguan-contras               1.0  1.0  1.0  
 mx-missile                              1.0  1.0  1.0  
 immigration                             1.0  1.0  1.0  
 synfuels-corporation-cutback            0.0  1.0  1.0  
 education-spending                      0.0  1.0  1.0  
 superfund-right-to-sue                  1.0  1.0  1.0  
 crime                                   1.0  1.0  1.0  
 duty-free-exports                       0.0  1.0  1.0  
 export-administration-act-south-africa  1.0  1.0  1.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

scaled_encoded_house_data = pd.DataFrame()

column_values = encoded_house_data.columns.values

column_values = column_values[:-1]

scaled_values = min_max_scaler.fit_transform(encoded_house_data[column_values])

for i in range(len(column_values)):
  scaled_encoded_house_data[column_values[i]] = scaled_values[:, i]

scaled_encoded_house_data[' export-administration-act-south-africa'] = encoded_house_data[' export-administration-act-south-africa']

In [ ]:
scaled_encoded_house_data.describe().T

count      mean       std  min  25%  \
Class Name                               435.0  0.386207  0.487440  0.0  0.0   
 handicapped-infants                     435.0  0.429885  0.495630  0.0  0.0   
 water-project-cost-sharing              435.0  0.558621  0.497123  0.0  0.0   
 adoption-of-the-budget-resolution       435.0  0.606897  0.489002  0.0  0.0   
 physician-fee-freeze                    435.0  0.406897  0.491821  0.0  0.0   
 el-salvador-aid                         435.0  0.521839  0.500098  0.0  0.0   
 religious-groups-in-schools             435.0  0.650575  0.477337  0.0  0.0   
 anti-satellite-test-ban                 435.0  0.581609  0.493863  0.0  0.0   
 aid-to-nicaraguan-contras               435.0  0.590805  0.492252  0.0  0.0   
 mx-missile                              435.0  0.526437  0.499876  0.0  0.0   
 immigration                             435.0  0.512644  0.500416  0.0  0.0   
 synfuels-corporation-cutback            435.0  0.344828  0.475859  0.0  0.0   
 education-spending                      435.0  0.393103  0.489002  0.0  0.0   
 superfund-right-to-sue                  435.0  0.537931  0.499133  0.0  0.0   
 crime                                   435.0  0.609195  0.488493  0.0  0.0   
 duty-free-exports                       435.0  0.400000  0.490462  0.0  0.0   
 export-administration-act-south-africa  435.0  0.857471  0.349994  0.0  1.0   

                                         50%  75%  max  
Class Name                               0.0  1.0  1.0  
 handicapped-infants                     0.0  1.0  1.0  
 water-project-cost-sharing              1.0  1.0  1.0  
 adoption-of-the-budget-resolution       1.0  1.0  1.0  
 physician-fee-freeze                    0.0  1.0  1.0  
 el-salvador-aid                         1.0  1.0  1.0  
 religious-groups-in-schools             1.0  1.0  1.0  
 anti-satellite-test-ban                 1.0  1.0  1.0  
 aid-to-nicaraguan-contras               1.0  1.0  1.0  
 mx-missile                              1.0  1.0  1.0  
 immigration                             1.0  1.0  1.0  
 synfuels-corporation-cutback            0.0  1.0  1.0  
 education-spending                      0.0  1.0  1.0  
 superfund-right-to-sue                  1.0  1.0  1.0  
 crime                                   1.0  1.0  1.0  
 duty-free-exports                       0.0  1.0  1.0  
 export-administration-act-south-africa  1.0  1.0  1.0

In [ ]:
features = scaled_encoded_house_data.drop([' export-administration-act-south-africa'], axis=1)
target = scaled_encoded_house_data[' export-administration-act-south-africa']
print(features.shape)
print(target.shape)

(435, 16)
(435,)


In [ ]:
features_copy = features.copy()
target_copy = target.copy()

In [ ]:
from  sklearn.model_selection import train_test_split
x_train, x_test, Y_train, Y_test = train_test_split(features, target, test_size=0.2)

print(x_train.shape,Y_train.shape, x_test.shape, Y_test.shape)

(348, 16) (348,) (87, 16) (87,)


In [ ]:
import numpy as np

X_train = x_train.values
X_test = x_test.values
y_train = Y_train.values
y_test = Y_test.values


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_p = clf.predict(X_test)
acc = accuracy_score(y_test, y_p)
print("Using SK Learn Decision Tree", acc)

Using SK Learn Decision Tree 0.7931034482758621


In [ ]:

import numpy as np
import random
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import pandas as pd


# Decision Tree Class Implementation
class DecisionTree:

    def __init__(self, max_depth=None, min_samples_split=None, min_samples_leaf=None, max_features=None):
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.min_samples_leaf = min_samples_leaf
        self.max_features = max_features

    def gini(self, labels):
        unique, counts = np.unique(labels, return_counts=True)
        proportions = counts / np.sum(counts)
        return 1 - np.sum(proportions ** 2)

    def split(self, X, y, feature_idx, threshold):
        left_idxs = np.where(X[:, feature_idx] <= threshold)[0]
        right_idxs = np.where(X[:, feature_idx] > threshold)[0]
        left_X, left_y = X[left_idxs], y[left_idxs]
        right_X, right_y = X[right_idxs], y[right_idxs]
        return left_X, left_y, right_X, right_y

    def best_split(self, X, y):
        best_feature_idx, best_threshold, best_gini = None, None, np.inf
        features = np.arange(X.shape[1])
        if self.max_features is not None and self.max_features <= X.shape[1]:
            features = np.random.choice(features, size=int(self.max_features), replace=False)
        for feature_idx in features:
            thresholds = np.unique(X[:, feature_idx])
            for threshold in thresholds:
                left_X, left_y, right_X, right_y = self.split(X, y, feature_idx, threshold)
                if len(left_y) == 0 or len(right_y) == 0:
                    continue
                if self.min_samples_leaf is not None:
                    if len(left_y) < self.min_samples_leaf or len(right_y) < self.min_samples_leaf:
                        continue
                left_gini = self.gini(left_y)
                right_gini = self.gini(right_y)
                weighted_gini = (len(left_y) / len(y)) * left_gini + (len(right_y) / len(y)) * right_gini
                if weighted_gini < best_gini:
                    best_feature_idx = feature_idx
                    best_threshold = threshold
                    best_gini = weighted_gini
        return best_feature_idx, best_threshold

    def fit(self, X, y, depth=0):
        if depth == self.max_depth or len(np.unique(y)) == 1:
            return np.bincount(y).argmax()
        if self.min_samples_split is not None and len(y) < self.min_samples_split:
            return np.bincount(y).argmax()
        if self.min_samples_leaf is not None and len(y) < 2 * self.min_samples_leaf:
            return np.bincount(y).argmax()
        feature_idx, threshold = self.best_split(X, y)
        if feature_idx is None:
            return np.bincount(y).argmax()
        left_X, left_y, right_X, right_y = self.split(X, y, feature_idx, threshold)
        left_subtree = self.fit(left_X, left_y, depth + 1)
        right_subtree = self.fit(right_X, right_y, depth + 1)
        return {'feature_idx': feature_idx, 'threshold': threshold, 'left': left_subtree, 'right': right_subtree}

    def predict(self, X, tree):
        if isinstance(tree, np.int64):
            return tree
        feature_idx, threshold = tree['feature_idx'], tree['threshold']
        if X[feature_idx] <= threshold:
            if isinstance(tree['left'], np.int64):
                return tree['left']
            else:
                return self.predict(X, tree['left'])
        else:
            if isinstance(tree['right'], np.int64):
                return tree['right']
            else:
                return self.predict(X, tree['right'])



In [ ]:

# <=================================== Decision Tree Without FS and Without HP Optimization ========================>
dt = DecisionTree()
tree_dt = dt.fit(X_train, y_train)
y_pred = [dt.predict(X, tree_dt) for X in X_test]

print("<================= Decision Tree without HP and without FS Optimization ===========================>")
accuracy = sum(y_pred == y_test) / len(y_test)
print("Accuracy without HP and without FS: ",  accuracy, "\n\n")


<================= Decision Tree without HP and without FS Optimization ===========================>
Accuracy without HP and without FS:  0.7931034482758621 




In [ ]:

# <========================================== Decision Tree With FS Optimization ==================================>
# Define the fitness function
def fitness_func(features):
    # Select the subset of features
    selected_features = X_train[:, np.array(features) == 1]

    clf = DecisionTree()
    tree = clf.fit(selected_features, y_train)

    selected_features_test = X_test[:, np.array(features) == 1]
    y_pred = [clf.predict(X, tree) for X in selected_features_test]

    accuracy = sum(y_pred == y_test) / len(y_test)
    # print(selected_features) # for debugging purpose
    return accuracy


# PSO for feature Selection
def PSO_for_feature_selection(fitness_func, num_particles, num_features, num_iterations):

    # Initialize the positions and velocities of the particles
    # generates a 2D NumPy array of size (num_particles, num_features),
    #  where each element is randomly sampled from the integers [0, 2)
    positions = np.random.randint(2, size=(num_particles, num_features))
    velocities = np.random.randint(2, size=(num_particles, num_features))

    # Initialize the personal best positions and fitness values
    personal_best_positions = positions.copy()
    personal_best_fitness_values = np.apply_along_axis(fitness_func, 1, personal_best_positions)

    # Initialize the global best position and fitness value
    global_best_index = np.argmax(personal_best_fitness_values)
    global_best_position = personal_best_positions[global_best_index]
    global_best_fitness_value = personal_best_fitness_values[global_best_index]

    # Set the PSO parameters
    inertia_weight = 0.7
    cognitive_component = 1.4
    social_component = 1.4

    # Start the PSO iterations
    for i in range(num_iterations):
        # Update the velocities of the particles
        new_velocities = (
            inertia_weight * velocities
            + cognitive_component * np.random.rand(num_particles, num_features) * (personal_best_positions - positions)
            + social_component * np.random.rand(num_particles, num_features) * (global_best_position - positions)
        )

        # Update the positions based on the velocities
        new_positions = np.where(new_velocities > 0.5, 1, 0)

        # Evaluate the fitness values of the new positions
        new_fitness_values = np.apply_along_axis(fitness_func, 1, new_positions)

        # Update the personal best positions and fitness values
        mask = new_fitness_values > personal_best_fitness_values
        personal_best_positions[mask] = new_positions[mask]
        personal_best_fitness_values[mask] = new_fitness_values[mask]

        # Update the global best position and fitness value
        index = np.argmax(personal_best_fitness_values)
        if personal_best_fitness_values[index] > global_best_fitness_value:
            global_best_index = index
            global_best_position = personal_best_positions[index]
            global_best_fitness_value = personal_best_fitness_values[index]

        # Update the velocities and positions
        velocities = new_velocities.copy()
        positions = new_positions.copy()

        # Print the current iteration's information
        print(f"Iteration {i + 1}:")
        print("Personal Best: ", personal_best_positions)
        print("Best Feature Subset:", global_best_position)
        print("Best Fitness Value:", global_best_fitness_value)
        print("--------------------------------------------")

    return global_best_position



# Test the PSO function for feature selection
num_particles = 10
num_features = features.shape[1]
num_iterations = 50

print("<================= Decision Tree with FS Optimization ===========================>")
best_feature_subset = PSO_for_feature_selection(fitness_func, num_particles, num_features, num_iterations)
print("Best Feature Subset:", best_feature_subset)
print("\n\n\n")






<================= Decision Tree with FS Optimization ===========================>
Iteration 1:
Personal Best:  [[1 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1]
 [0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1]
 [1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0]
 [0 0 1 1 0 0 0 1 1 0 1 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1]
 [0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0]
 [1 0 0 1 0 0 1 1 0 1 0 1 1 0 0 1]]
Best Feature Subset: [0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1]
Best Fitness Value: 0.8850574712643678
--------------------------------------------
Iteration 2:
Personal Best:  [[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1]
 [1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1]
 [0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1]
 [1 0 0 1 0 0 1 1 0 1 0 1 1 0 0 1]]
Best Feature Subse

In [ ]:

# <============================== Decision Tree with FS and HP Optimization ================================>

# Define the fitness function for DT with FS and HP optimization
def fitness_function_with_fs_and_hp(params, features = best_feature_subset):
    max_depth = int(params[0])
    min_samples_split = int(params[1])
    min_samples_leaf = int(params[2])
    max_features = int(params[3])

    # Select the subset of features
    selected_features = X_train[:, np.array(features) == 1]
    print(selected_features, best_feature_subset)

    if max_depth < 0:
        max_depth = max_depth * -1
    if min_samples_split < 0:
        min_samples_split = min_samples_split * -1
    if min_samples_leaf < 0:
        min_samples_leaf = min_samples_leaf * -1
    if max_features < 0:
        max_features = max_features * -1

    clf = DecisionTree(
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features
    )
    tree = clf.fit(selected_features, y_train)

    selected_features_test = X_test[:, np.array(features) == 1]
    y_pred = [clf.predict(X, tree) for X in selected_features_test]

    accuracy = sum(y_pred == y_test) / len(y_test)
    return accuracy


# Define the PSO function
def PSO_with_FS_and_HP(fitness_function_with_fs_and_hp, num_particles, num_dimensions, num_iterations, param_ranges):
    # Initialize the positions and velocities of the particles
    positions = np.random.uniform(*zip(*param_ranges), (num_particles, num_dimensions))
    velocities = np.random.uniform(-1, 1, (num_particles, num_dimensions))

    # Initialize the personal best positions and fitness values
    personal_best_positions = positions.copy()
    personal_best_fitness_values = np.apply_along_axis(fitness_function_with_fs_and_hp, 1, personal_best_positions)

    # Initialize the global best position and fitness value
    global_best_index = np.argmax(personal_best_fitness_values)
    global_best_position = personal_best_positions[global_best_index]
    global_best_fitness_value = personal_best_fitness_values[global_best_index]

    # Set the PSO parameters
    inertia_weight = 0.7
    cognitive_component = 1.4
    social_component = 1.4

    # Start the PSO iterations
    for i in range(num_iterations):
        # Update the velocities and positions of the particles
        new_velocities = (
            inertia_weight * velocities
            + cognitive_component
            * np.random.rand(num_particles, num_dimensions)
            * (personal_best_positions - positions)
            + social_component
            * np.random.rand(num_particles, num_dimensions)
            * (global_best_position - positions)
        )
        new_positions = positions + new_velocities

        # Evaluate the fitness values of the new positions
        new_fitness_values = np.apply_along_axis(fitness_function_with_fs_and_hp, 1, new_positions)

        # Update the personal best positions and fitness values
        mask = new_fitness_values > personal_best_fitness_values
        personal_best_positions[mask] = new_positions[mask]
        personal_best_fitness_values[mask] = new_fitness_values[mask]

        # Update the global best position and fitness value
        index = np.argmax(personal_best_fitness_values)
        if personal_best_fitness_values[index] > global_best_fitness_value:
            global_best_position = personal_best_positions[index]
            global_best_fitness_value = personal_best_fitness_values[index]

        # Update the velocities and positions
        velocities = new_velocities.copy()
        positions = new_positions.copy()

        # Print the current iteration's information
        print(f"Iteration {i + 1}:")
        print("Best Global Position:", global_best_position)
        print("Best Fitness Value:", global_best_fitness_value)
        print("--------------------------------------------")

    return global_best_position, global_best_fitness_value


# Define the parameter ranges
param_ranges = [(1, 10), (2, 20), (1, 10), (1, 4)]

num_particles = 10
num_dimensions = 4
num_iterations = 50

print("<================= Decision Tree with HP and with FS Optimization ===========================>")
best_hyperparameters, best_fitness_value = PSO_with_FS_and_HP(fitness_function_with_fs_and_hp, num_particles, num_dimensions, num_iterations, param_ranges)

print("Best Hyperparameters:")
print("max_depth:", int(best_hyperparameters[0]))
print("min_samples_split:", int(best_hyperparameters[1]))
print("min_samples_leaf:", int(best_hyperparameters[2]))
print("max_features:", int(best_hyperparameters[3]))
print("Best Fitness Value:", best_fitness_value)
print("\n\n")



<================= Decision Tree with HP and with FS Optimization ===========================>
[[1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 1.]] [0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1]
[[1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 1.]] [0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1]
[[1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 1.]] [0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1]
[[1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 1.]] [0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1]
[[1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 1.]] [0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1]
[[1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 1.]] [0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1]
[[1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 1.]] [0 0 0 1 0 0 0 1 0 0 0 0 1 0 